### ISSUE TITLE
Mod User installation issue

### ISSUE THREAD

**Issue by Swimdudd** [ividyon/Gideon#1]
When I try to use the setup short cut for a mod, it kicks back these errors after running: https://ibb.co/qd9rjQr . have the current .NET framework installed, tried a fresh install of game and mod and nothing worked. sorry if this isnt where I should be asking this, thank you for your time.

**Comment by ividyon** [comment]
Try deleting the menu\01_common.tpfbnd.dcx file, maybe verify your Steam ER game files, and try again.
